### ISSUE TITLE
When flags expire do we really need every single application to start erroring?

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-feature-flags-client#55]
Got like 7 emails……

Wouldn't it be better if we just had a single sensu alert instead?

**Comment by matthew-andrews** [comment]
[expose an endpoint of radiator or something that 5xx'd when we had an expired flag, which would then trigger sensu]

**Comment by matthew-andrews** [comment]
cc @wheresrhys (although i don't mind doing this work)

**Comment by wheresrhys** [comment]
maybe combined with a search for the flag added to the CODE bit of radiator too, which'd also be a better way of finding the location of the offending use of the flag. (which is what these alerts are for actually; not to let you know a flag has expired, but to tell you to clean up after it).

**Comment by wheresrhys** [comment]
Alerting on the length of a search for unused flags in the codebase (e.g. don't allow more than 10 results) would be a closer equivalent to this functionality in fact

**Comment by aintgoin2goa** [comment]
This alerting has been removed from here now to help slim down the client - we can use monitoring for this.
